### DISCUSSION TITLE
tried multiple configs.... artisan file not found and no web access

### DISCUSSION THREAD

**Discussion by IxsharpxI** [Kovah/LinkAce#391] [Support]
Hello, 

So i have tried the simple, and advanced versions, as well as the advanced without nginx since I have a reverse proxy else where. Everytime I get stuck at the same spot to generate a key.

 I get the same output regardless of install:

Could not open input file: artisan

Also, with or without nginx I have not been able to access the GUI.. will this not initiate until after restarted with App Key?

**Comment by Kovah** [comment]
Could you post the exact commands you used to generate the application key? Sounds like there is something wrong with them.

**Reply by IxsharpxI** [reply]
Sure thing. I tried to run inside the app container but didn't like it. so from the docker host I run the following:

`sudo docker exec linkace_app_1 php artisan key:generate`

**Reply by Kovah** [reply]
Could you take a look at https://github.com/Kovah/LinkAce/discussions/393

**Reply by IxsharpxI** [reply]
Thank you that did get through to the next step. However, no we trying to access the webui I just get the nginx welcome page? I have a feeling maybe something my nginx.conf file as it just shows up blank in the host volume. I added my docker-compose.yaml

edit: wow the format got bonk'd

`version: "3"

services:
  # --- MariaDB
  db:
    image: mariadb:10.5
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=linkace
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=linkace
    volumes:
      - /home/docker/linkace/db:/var/lib/mysql

  # --- LinkAce Image with PHP 7.4
  app:
    image: linkace/linkace:latest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /home/docker/linkace/.env:/app/.env
      - /home/docker/linkace/linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use local backups
      - /home/docker/linkace/backups:/app/storage/app/backups

  # --- nginx
  nginx:
    image: bitnami/nginx:1.19
    restart: unless-stopped
    ports:
      - "80:8080"
      #- "443:8443"
    depends_on:
      - app
    volumes:
      - linkace_app:/app
      # Replace `nginx.conf` with `nginx-ssl.conf` and remove the hash from the following line
      # if you want to use HTTPS for this container
      - /home/docker/linkace/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro

  # --- Redis
  redis:
    image: bitnami/redis:6.0
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=

volumes:
  linkace_app:
  linkace_logs:
  db:
    driver: local`

**Reply by Kovah** [reply]
Can you verify that the nginx configuration got mounted correctly inside the container? `docker exec linkace_nginx_1 ls -la /opt/bitnami/nginx/conf/server_blocks/` should display the file.

**Reply by IxsharpxI** [reply]
```
total 13
drwxrwxr-x 2 root root  3 Feb 10 15:26 .
drwxrwxr-x 4 root root 19 Jul 29  2021 ..
-rw-rw-r-- 1 1000 1000  0 Feb  9 18:24 linkace.conf
chandler@dockertemp:/home/docker/linkace$ sudo docker exec linkace_nginx_1 cat /opt/bitnami/nginx/conf/server_blocks/linkace.conf
chandler@dockertemp:/home/docker/linkace$ 
```

It appears to be loaded however blank, similar to the host volume nginx.conf. So if I copy a paste config from the code there and reboot maybe that will load it into linkace.conf?

**Reply by IxsharpxI** [reply]
no dice for that but it did load it into linkace.conf after that

**Comment by martadinata666** [comment]
Test simplest way

```
version: "3"
services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=linkace
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=linkace
    volumes:
      - /home/docker/linkace/db:/var/lib/mysql

  app:
    image: linkace/linkace:latest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /home/docker/linkace/.env:/app/.env
      - /home/docker/linkace/linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use local backups
      - /home/docker/linkace/backups:/app/storage/app/backups
    ports:
      - 25000:80 #linkace itself nginx

  # Is this for reverse proxy?
  nginx:
    image: bitnami/nginx:1.19
    restart: unless-stopped
    ports:
      - "80:8080"
      #- "443:8443"
    depends_on:
      - app
    volumes:
      #- linkace_app:/app
      # Replace nginx.conf with nginx-ssl.conf and remove the hash from the following line
      # if you want to use HTTPS for this container
      - /home/docker/linkace/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro

  redis:
    image: bitnami/redis:6.0
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=
```

Check if you can access it from port 25000. As linkace got the web server `nginx` itself.
