### DISCUSSION TITLE
Issue after installation: Could not open the input file: artisan

### DISCUSSION THREAD

**Discussion by b3nd1k** [Kovah/LinkAce#393] [Support]
Hey! I've Docker running on an Ubuntu server and I recently tried installing LinkAce. I instarlled LinkAce using portainer and after I had pulled the image and it was running, I SSHed into my server and tried running the command `docker exec linkace php artisan key:generate`

However, I got the following response `Could not open input file: artisan`. Any idea how to fix this?

**Comment by Kovah** [comment]
Could you please post the output of those both commands
```
docker exec linkace ls -la
```
and 
```
docker image ls | grep linkace
docker image inspect [id of the linkace image]
```

**Reply by b3nd1k** [reply]
Absolutely!

root@network-server:~# docker exec linkace ls -la
```
total 16
drwxr-xr-x    3 root     root          4096 Feb  9 20:02 .
drwxr-xr-x    1 root     root          4096 Feb  9 20:22 ..
-rwxr-xr-x    1 root     root          3215 Feb  9 20:04 .env
drwxr-xr-x    3 root     root          4096 Feb  9 19:57 storage
```

```
root@network-server:~# docker image ls | grep linkace
linkace/linkace                        latest    4b0e73aa6afb   2 weeks ago    521MB
```

The log of the last command is quite long, so I have uploaded it here: https://ghostbin.com/7kjxg

**Reply by Kovah** [reply]
According to the inspect command you have the exact same image I have, so they should be equal. It's weird that you only have .env and storage in your directory.
Could you try `docker exec linkace pwd`? It should return `/app`.

**Reply by b3nd1k** [reply]
You're correct. The command you asked me to try, returned `/app.` 

In Portainer, this is my mapping for the .env-file.
container: `/.env`
path: `/mnt/volume/appdata/linkace/.env`

If I try to remove the "/" before the .env, I get a message saying ```
Failure
invalid volume specification: '/mnt/volume/appdata/linkace/.env:.env': invalid mount config for type "bind": invalid mount path: '.env' mount path must be absolute```

**Reply by Kovah** [reply]
Yeah that won't work. Files must be mounted into the /app directory, so it would be `/app/.env`. But maybe recreate the container so all wrongly mounted files inside the container are gone.

**Reply by b3nd1k** [reply]
I tried to recreate the container with the new paths, but I still get the same error as before `could not open input file: artisan `. Here are all my paths

container: `/app/.env`
host:` /mnt/volume/appdata/linkace/.env`

container: `/app`
host: `/mnt/volume/appdata/linkace`

container: `/app/storage/logs`
host: `/mnt/volume/appdata/linkace/storage/logs`

**Reply by martadinata666** [reply]
Well you overriding /app to your local, that should be contain artisan and it friends.

on laravel framework web, usually only storage, .env, and database.

**Reply by b3nd1k** [reply]
I'm sorry, I don't understand. What do I need to change?

**Reply by martadinata666** [reply]
remove the
```
container: /app
host: /mnt/volume/appdata/linkace
```

**Reply by b3nd1k** [reply]
Thank you! After removing the said container, it's up and running and I was able to run the `docker exec linkace php artisan key:generate` command.  However, I am not able to access the domain. Either through MY-IP:PORT or through a reverse proxy. I ran `docker ps` which returned 

```
CONTAINER ID   IMAGE                                         COMMAND                  CREATED         STATUS                  PORTS                                                                                                                                                                                    NAMES
9a501809c5c1   linkace/linkace:latest                        "docker-php-entrypoi…"   9 minutes ago   Up 9 minutes            9000/tcp, 0.0.0.0:8585->80/tcp, :::8585->80/tcp    
```

In NginxProxyManager, I've entered in the IP of the continaer as well as the port (80) and chosen to forward it to bookmarks.mydomain.com, just like I do with my other containers such as Bookstack. However, when I try to access IP:port or bookmarks.mydomain.com, I get "`502 Bad Gateway`"-error code. For the sake of trying, I've also tried to forward port 9000 and 8585, but no luck there. Any ideas? I haven't done it anything any different than I would with any other container.

**Reply by martadinata666** [reply]
how it your ports?
```
  ports
    - 8585:80
```
Should be enough, yeah 502 mean npm cant connect to designated back url.

**Reply by b3nd1k** [reply]
That's correct, my ports are 8585:80. When I tried 8080:80, Portainer gave  me the error `Request failed with status code 500`. I've tried to open up and let port 8585 through my firewall and try to access LinkAce through external-IP:8585, but the connection times out.

**Reply by martadinata666** [reply]
Can you post your compose?

**Reply by b3nd1k** [reply]
Exported from Portainer

```
version: "3"
services:
  linkace:
    container_name: linkace
    environment:
      - GPG_KEYS=SENSORED
    hostname: linkace
    image: linkace/linkace:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    networks:
      - milkyway
    ports:
      - 8585:80/tcp
    restart: unless-stopped
    volumes:
      - /mnt/volume/appdata/linkace/storage/logs:/app/storage/logs
      - /mnt/volume/appdata/linkace/.env:/app/.env
    working_dir: /app
networks:
  milkyway:
    external: true
```

**Reply by martadinata666** [reply]
Dunno how portainer add network thing, try to test with it own network instead milkyway
```
version: "3"
services:
  linkace:
    container_name: linkace
    environment:
      - GPG_KEYS=SENSORED
    hostname: linkace
    image: linkace/linkace:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    networks:
      - linkace
    ports:
      - 8585:80/tcp
    restart: unless-stopped
    volumes:
      - /mnt/volume/appdata/linkace/storage/logs:/app/storage/logs
      - /mnt/volume/appdata/linkace/.env:/app/.env
    working_dir: /app
networks:
  linkace:
    name: linkace
  #milkyway:
  # external: true
```
