### DISCUSSION TITLE
New LinkAce installation - Docker Advanced

### DISCUSSION THREAD

**Discussion by Riprock** [Kovah/LinkAce#413] [Support] [answered]
Hello
So as i Was going though the docker advanced installation for LinkAce, I followed along with the instructions but I came to find that it wasn't starting the bitnami/nginx container while all the other ones were running. Digging into the logs it seems that there is a failure with this error
nginx 03:34:04.97 INFO  ==> ** Starting NGINX **
2022/03/11 03:34:04 [crit] 1#1: pread() "/opt/bitnami/nginx/conf/server_blocks/linkace.conf" failed (21: Is a directory)
nginx: [crit] pread() "/opt/bitnami/nginx/conf/server_blocks/linkace.conf" failed (21: Is a directory)

Not seeing any other errors besides this

**Comment by martadinata666** [comment, marked as answer]
is the `nginx.conf` there? in the directory with docker-compose.yml

**Reply by Riprock** [reply]
No. I didnt realize I had to include an nginx.conf file. Didint see it in the instructions for setting up

**Comment by AlexTu2** [comment]
I had a similar issue,
I was turning SSL certs on and renamed my `nginx.conf ` to `nginx-ssl.conf`

In the `docker.compose.yaml` file I had to change the 
`- ./nginx.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro`
to
`- ./nginx-ssl.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro`

code block:
```yaml
  # --- nginx
  nginx:
    image: bitnami/nginx:1.19
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:8080"
      #- "0.0.0.0:443:8443"
    depends_on:
      - app
    volumes:
      - linkace_app:/app
      # Replace `nginx.conf` with `nginx-ssl.conf` and remove the hash from the following line
      # if you want to use HTTPS for this container
      - ./nginx-ssl.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro
```
