### DISCUSSION TITLE
Help: SQLSTATE[HY000] [1045] Access denied for user 'linkace'@'172.18.0.3'

### DISCUSSION THREAD

**Discussion by b52src** [Kovah/LinkAce#481] [Support] [answered]
Having issues completing setup after deploying with the below compose(passwords and key are changed). I deployed without a .env but had to add to the /app directory to get the setup to start.  However I'm getting the following when I try and complete the database setup:

Database could not be configured. Please check your connection details. Details: SQLSTATE[HY000] [1045] Access denied for user 'linkace'@'172.18.0.3' (using password: YES) (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

```
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=xyz!!
      - MYSQL_USER=linkace
      - MYSQL_PASSWORD=xyz!!
      - MYSQL_DATABASE=linkacedb
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:8085:80"
      #- "0.0.0.0:443:443"
    environment:
      - APP_KEY=base64:123xyz
      - DB_HOST=db
      - DB_DATABASE=linkacedb
      - DB_USERNAME=linkace
      - DB_PASSWORD=xyz!!
    volumes:
      - linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro
      # Remove the hash of the following line if you want to use local backups
      #- ./backups:/app/storage/app/backups


volumes:
  linkace_logs:
  db:
    driver: local
```
