### DISCUSSION TITLE
Database could not be configured.

### DISCUSSION THREAD

**Discussion by bellsey** [Kovah/LinkAce#564] [Support]
I'm trying to get Linkace running on my Synology NAS via Docker.
Got everything working but now I'm stuck at configuring the Database with this error:

_Database could not be configured. Please check your connection details. Details: SQLSTATE[HY000] [2002] Connection refused (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')_

My .env is this
```
DB_CONNECTION=mysql
DB_HOST=172.17.0.1
DB_PORT=3306
DB_DATABASE=linkace
DB_USERNAME=user
DB_PASSWORD=*******
```
And my docker-compose.yml is this

```
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    network_mode: bridge
    depends_on:
      - db
    ports:
      - "8080:80"

    volumes:
      - /volume1/docker/linkace/.env:/app/.env

volumes:
  linkace_logs:
  db:
    driver: local
```

I'm assuming there's some type of connection issue, but I can't figure it out and I'm probably missing something obvious. 
I've seen similar issues reported here and followed some solution steps but still can't get it working

Any help appreciated, thanks in advance
