### DISCUSSION TITLE
Having trouble running LinkAce with Caddy

### DISCUSSION THREAD

**Discussion by blipdrifter** [Kovah/LinkAce#659] [Support] [answered]
Hi! I just found out about LinkAce not too long ago and decided to try installing it on my Caddy server. Just one small problem: I can't figure out how to get it working with either the Docker or non-Docker install methods.

Whenever I tried to use Docker, it just gave me an error that the port was already in use (by Caddy -- I have a seperate web server I want to use alongside LinkAce because I have a static site on the same VPS), and as a result the nginx container failed to start. So I tried installing it manually via PHP and my Caddyfile, but I've futzed around with it for over an hour at this point and I can't get any further than a blank page when I try to visit the subdomain that's supposed to point to LinkAce.

Can anyone help me get LinkAce working with Caddy? I'd really appreciate it!

**Comment by Kovah** [comment]
I have not tested LinkAce together with Caddy in any setup without Docker, but with Docker there should be no problems running it. If you are using Caddy in front of LinkAce, change the port of the LinkAce container to any other port than 80 or 443:

```yml

  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:80"
```
and then point Caddy to that new port, `8080` in this case.

**Reply by blipdrifter** [reply]
Tried setting that line in docker-compose.yml to '0.0.0.0:8090:80' (it was already set to 0.0.0.0) and that seems to have done nothing (although all the containers start properly now, so that's something). I set my Caddyfile to reverse proxy the port in a specific directory and I just get a blank page. Tried visiting the port directly on my domain, just gives me an 'unable to connect' error. Ran `docker-compose up` without the `-d` flag to see what was up, and I noticed that the last line it spits out before doing nothing is 'Starting NGINX...', which I'm not sure is normal or not. Still not sure what's up...

**Reply by Kovah** [reply]
I am not sure about Caddy, haven't used it much.

From what I know a Caddyfile like this _should_ work:

```
example.com {
    reverse_proxy localhost:8090
}
```

**Reply by blipdrifter** [reply]
Tried it, didn't work. Made sure the port was right and everything. `docker-compose logs` reports no issues. Tried accessing the port on my domain directly, no such luck.

**Reply by Kovah** [reply]
Guess I'm out of guessing then. What exactly is being returned when you open the page with the port used in Docker, instead of whatever Caddy is configured to?

You could try to completely recreate the containers:
```
docker-compose down
docker-compose up
```

**Reply by blipdrifter** [reply]
Just tried that, got stuck on `** Starting NGINX **` again. Checked the Caddy access logs for the subdomain and apparently it's spitting out 502 errors? Here's where the Docker logs stop for me:

![image](https://github.com/Kovah/LinkAce/assets/11656143/2d3ee4f5-1db7-4849-b755-c4988a46054d)

Also tried switching between port 8080 and port 9080 in both the Caddyfile and docker-compose.yml, no such luck. Is it supposed to be set to `[port]:80` in the compose file?

**Reply by Kovah** [reply]
Starting NGINX as the last line is not wrong.
But if you use the LinkAce simple image, why is there a separate nginx container? You can either use the advanced image with a separate nginx, or the simple image that doesn't need anything else. Did you switch images while trying to get everything running?

**Reply by Kovah** [reply]
This is what a docker compose file should look like. You can change the port of the app container to something else than 80 to run behind a load balancer, but anything else should stay as it is.

```yaml
version: "3"
services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql
     
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:80:80" # <<< you may change this line to `0.0.0.0:8080:80`
    volumes:
      - ./.env:/app/.env
      - ./backups:/app/storage/app/backups
      - linkace_logs:/app/storage/logs

volumes:
  linkace_logs:
  db:
    driver: local

```
