### DISCUSSION TITLE
SQLSTATE[HY000] [1045] Access denied for user 'dbuser'@'192.168.240.3'

### DISCUSSION THREAD

**Discussion by rcjcarr** [Kovah/LinkAce#726] [Support] [answered]
Also struggling with this. Getting all green check marks on the previous steps. Running Docker under OMV6 on a RPi4.
![image](https://github.com/Kovah/LinkAce/assets/50344858/354f3e98-39bc-4f69-914c-fe98c19f6202)

```yml
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=abcd
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=abcd
      - MYSQL_DATABASE=linkacedb
      - APP_KEY=base64:f9Z5eyPvtVzd47WK0fhjeWyz0gYgijL/oxoaziSSObs=
      - PUID=1001
      - PGID=100
    volumes:
      - /SSD/appdata/linkace/db:/var/lib/mysql

#    ports:
#      - 3506:3306

  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:85:80"
      #- "0.0.0.0:443:443"
    volumes:
      - /SSD/appdata/linkace/.env:/app/.env
      - /SSD/appdata/linkace/backups:/app/storage/app/backups
      - /SSD/appdata/linkace/linkace_logs:/app/storage/logs

      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro
    environment:      
      - DB_HOST=db
      - DB_DATABASE=linkacedb
      - DB_USERNAME=dbuser
      - DB_PASSWORD=abcd
      - APP_KEY=base64:f9Z5eyPvtVzd47WK0fhjeWyz0gYgijL/oxoaziSSObs=
      - PUID=1001
      - PGID=100
volumes:
  linkace_logs:
  db:
    driver: local
```
.env file:
```
      1 ## LINKACE CONFIGURATION
      2
      3 ## Basic app configuration
      4 # The app key is generated later, please leave it like that
      5 APP_KEY=base64:f9Z5eyPvtVzd47WK0fhjeWyz0gYgijL/oxoaziSSObs=
      6
      7 ## Configuration of the database connection
      8 ## Attention: Those settings are configured during the web setup, please do not modify them now.
      9 # Set the database driver (mysql, pgsql, sqlsrv, sqlite)
     10 DB_CONNECTION=mysql
     11
     12 # Set the host of your database here
     13 DB_HOST=127.0.0.1
     14 # DB_HOST=db
     15
     16 # Set the port of your database here
     17 DB_PORT=3306
     18
     19 # Set the database name here
     20 DB_DATABASE=linkacedb
     21
     22 # Set both username and password of the user accessing the database
     23 DB_USERNAME=dbuser
     24
     25 # Wrap your password into quotes (") if it contains special characters
     26 DB_PASSWORD=abcd
     27
     28 # Extra stuff
     29 APP_DEBUG=true
     30 FORCE_HTTPS=false
     31 # SET_COMPLETED=false
     32 # SESSION_LIFETIME=10080
```

**Comment by rcjcarr** [comment]
Noticed that the linkace app recursively changes db file ownership to openmediavault-webgui.... very odd.
Group is spi, also odd.
```
$ls -al db
drwxrwsrwx 6 openmediavault-webgui spi        4096 Nov 15 15:33 .
drwxr-sr-x 5 rc                    users      4096 Nov 15 15:22 ..
-rwxrwxrwx 1 openmediavault-webgui spi    18161664 Nov 15 15:31 aria_log.00000001
-rwxrwxrwx 1 openmediavault-webgui spi          52 Nov 15 15:31 aria_log_control
-rw-rw---- 1 openmediavault-webgui spi           9 Nov 15 15:33 ddl_recovery.log
-rw-rw---- 1 openmediavault-webgui spi         872 Nov 15 15:31 ib_buffer_pool
-rwxrwxrwx 1 openmediavault-webgui spi   100663296 Nov 15 15:33 ib_logfile0
-rwxrwxrwx 1 openmediavault-webgui spi    12582912 Nov 15 15:31 ibdata1
-rw-rw---- 1 openmediavault-webgui spi    12582912 Nov 15 15:33 ibtmp1
drwxrwsrwx 2 openmediavault-webgui spi        4096 Nov 14 15:04 linkace
-rwxrwxrwx 1 openmediavault-webgui spi           0 Nov 14 15:04 multi-master.info
drwxrwsrwx 2 openmediavault-webgui spi        4096 Nov 14 15:04 mysql
-rwxrwxrwx 1 openmediavault-webgui spi          14 Nov 14 15:04 mysql_upgrade_info
drwxrwsrwx 2 openmediavault-webgui spi        4096 Nov 14 15:04 performance_schema
drwxrwsrwx 2 openmediavault-webgui spi       12288 Nov 14 15:04 sys
```

**Comment by Kovah** [comment]
Hi, did you change the password in between the setup? The troubleshooting for invalid credentials mostly went into such a direction.
If you are familiar with MySQL you could enable the port and try to connect with the user `root` and the password you set. If that does not work, there must be something wrong with MySQL itself. In that case, stop the whole thing with `docker compose stop` and delete the MySQL data stored in `/SSD/appdata/linkace/db`. After that, start up everything and try again.

Also, make sure that `/SSD/appdata/linkace/db` is writable, otherwise he MySQL service will likely not work correctly.

Another thing: please remove all environment variables from the app if you use a .env file. It only mixes things up. LinkAce also does not support setting a user or group out of the box. That's also the reason for the weird permissions. The user inside the container coincidentially has the same ID as openmediavault-webgui.

**Reply by rcjcarr** [reply]
Decided to separate the db from the app using two docker stacks. Created and started the database first using:
linkacedb.yml:
```yml
version: "3"

services:
  mariadb:
  # --- MariaDB
    image: mariadb:10.7
    container_name: linkacedb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=linkace
#    ports:
#      - 3506:3306
    network_mode: bridge
    restart: always
    volumes:
      - /SSD/appdata/linkacedb:/var/lib/mysql
```
Logged-in the container using:
`docker container exec -it linkacedb bash`

Logged-in the database using:
`mysql -u root -p`

Created user:
`CREATE USER 'linkace' IDENTIFIED BY 'linkace';`

Created linkace database:
`CREATE DATABASE IF NOT EXISTS linkace;`

Created user:
`GRANT ALL PRIVILEGES ON linkace.* TO 'linkace' IDENTIFIED BY 'linkace';`

`quit`

![image](https://github.com/Kovah/LinkAce/assets/50344858/42057a1a-fbe6-4e44-9e69-cb31e12dcd69)

Next created container for the linkace app:
```yml
version: "3"

version: "3"

services:
  # --- LinkAce Image with PHP and nginx
  linkace:
    image: linkace/linkace:simple
    container_name: linkace
    restart: unless-stopped
    ports:
      - "0.0.0.0:85:80"
      #- "0.0.0.0:443:443"
    volumes:
      - /SSD/appdata/linkace/.env:/app/.env
      - /SSD/appdata/linkace/backups:/app/storage/app/backups
      - /SSD/appdata/linkace/linkace_logs:/app/storage/logs

 

      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro
    environment:      
#      - DB_HOST=127.0.0.1

      - DB_DATABASE=linkacedb
      - DB_USERNAME=linkace
      - DB_PASSWORD=linkace
      - APP_KEY=base64:f9Z5eyPvtVzd47WK0fhjeWyz0gYgijL/oxoaziSSObs=
      
    network_mode: bridge
volumes:
  linkace_logs:
```
Finally update the .env file, most notably changed the DB_DATABASE variable to point to the db container:
```
## LINKACE CONFIGURATION

## Basic app configuration
# The app key is generated later, please leave it like that
APP_KEY=base64:f9Z5eyPvtVzd47WK0fhjeWyz0gYgijL/oxoaziSSObs=

## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv, sqlite)
DB_CONNECTION=mysql

# Set the host of your database here
DB_HOST=127.0.0.1

# Set the port of your database here
DB_PORT=3306

# Set the database name here
DB_DATABASE=linkacedb

# Set both username and password of the user accessing the database
DB_USERNAME=linkace

# Wrap your password into quotes (") if it contains special characters
DB_PASSWORD=linkace

# Extra stuff
APP_DEBUG=true
FORCE_HTTPS=false
```

![image](https://github.com/Kovah/LinkAce/assets/50344858/39feb49c-e9ee-4af5-97ad-1f383c5c1aa3)

Now getting the same error:
![image](https://github.com/Kovah/LinkAce/assets/50344858/079bc485-2d5e-4f70-b220-049744d44fed)


Not sure about the value that DB_HOST should have...

**Reply by Kovah** [reply]
That looks quite good so far. When you separate services into different files, you need to connect them with a Docker network. Otherwise each one of the containers will not be able to see the others.

Details: https://docs.docker.com/compose/networking/

**Reply by rcjcarr** [reply]
Hmm, I thought that was the purpose of the `network_mode: bridge` directive. Yacht reports linkace IP at 172.17.0.4, and linkacedb at 172.17.0.3.

**Reply by rcjcarr** [reply]
`docker network ls`:
```
NETWORK ID     NAME                      DRIVER    SCOPE
8590d8abc050   bridge                    bridge    local
33c1f2d3a11f   cloudflare-ddns_default   bridge    local
37666abe95e4   freshrss_default          bridge    local
02088d8fa39d   host                      host      local
38cfbc368e78   nginx-proxy               bridge    local
bbb9f1fa363c   none                      null      local
9937a7126d33   stirling-pdf_default      bridge    local
d83e46ab5cd5   yacht_default             bridge    local
```

**Reply by rcjcarr** [reply]
Added the following to both .yml files as I eventually want LinkAce to be public facing:
```yml
networks:
   default:
      name: nginx-proxy
      external: true
```
Now getting the account setup page:
![image](https://github.com/Kovah/LinkAce/assets/50344858/f2205901-a476-4763-a60d-479b97290d48)

**Reply by rcjcarr** [reply]
At the Dashboard now so all probably ok. Thanks for your help.

**Reply by rcjcarr** [reply, marked as answer]
Final configuration is as below, with mods for NGINX reverse proxy manager running on the some host (RPi4)...
.env:
```raw
## LINKACE CONFIGURATION

## Basic app configuration
# The app key is generated later, please leave it like that
APP_KEY=base64:f9Z5eyPvtVzd47WK0fhjeWyz0gYgijL/oxoaziSSObs=

## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv, sqlite)
DB_CONNECTION=mysql

# Set the host of your database here
DB_HOST=linkacedb

# Set the port of your database here
DB_PORT=3306

# Set the database name here
DB_DATABASE=linkace

# Set both username and password of the user accessing the database
DB_USERNAME=linkace

# Wrap your password into quotes (") if it contains special characters
DB_PASSWORD=linkace

# Extra stuff
APP_DEBUG=true
FORCE_HTTPS=false
```
Database .yml:
```yml
version: "3"

services:
  linkacedb:
  # --- MariaDB
    image: mariadb:10.7
    container_name: linkacedb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=linkace
#    ports:
#      - 3506:3306
#    network_mode: bridge
    restart: always
    volumes:
      - /SSD/appdata/linkacedb:/var/lib/mysql

volumes:
    linkacedb:
      driver: local

networks:
   default:
      name: nginx-proxy
      external: true
```
App .yml:
```yml
version: "3"

services:
  # --- LinkAce Image with PHP and nginx
  linkace:
    image: linkace/linkace:simple
    container_name: linkace
    restart: unless-stopped
#    ports:
#      - "0.0.0.0:85:80"
      #- "0.0.0.0:443:443"
    volumes:
      - /SSD/appdata/linkace/.env:/app/.env
      - /SSD/appdata/linkace/backups:/app/storage/app/backups
      - /SSD/appdata/linkace/linkace_logs:/app/storage/logs

 

      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro
    environment:      
#      - DB_HOST=127.0.0.1

      - DB_DATABASE=linkace
      - DB_USERNAME=linkace
      - DB_PASSWORD=linkace
      - APP_KEY=base64:f9Z5eyPvtVzd47WK0fhjeWyz0gYgijL/oxoaziSSObs=
      
#    network_mode: bridge
volumes:
  linkace_logs:

networks:
   default:
      name: nginx-proxy
      external: true
```

**Reply by Kovah** [reply]
Glad it worked out! Let me know in case you have any other issues. 🥳

**Comment by bryanhunwardsen** [comment]
I was trying to stand-up a fresh docker advanced install of 1.13.0 and am got the same auth error during set-up=>DB Config as the OP.

I had made the following changes from the stock adv files:

.env
-set DB_PASSWORD
-set REDIS_PASSWORD
-add SESSION_DRIVER=redis
-add CACHE_DRIVER=redis

docker-compose.yaml
-change: nginx:ports:
--from: "0.0.0.0:80:8080"
--to: "0.0.0.0:9000:8080"
#port 80 already bound (nginix-proxy-manager - in its own docker subnet)
But I am not using npm to access linkace.

What I eventually found was that I needed to explicitly map db (and possibly logs) to local dir.
This is where environment may be an undocumented headache, Im using Container Manger in Synology DSM 7.2.
in this case I needed to manually create the folders and map ./db:/var/lib/mysql

This allowed for the adv version to finally get past the above screen/error.
However, although every indication points to it being the latest release when you view the dashboard it warns v"1.11.1 => 1.13.0 available" - I had blown away entire install/artifacts/volumes to pull and build a clean version but made no difference.
This may be a bug in adv, a bug in linkace for a synology specific deployment... I dont know.

I blew it all away and used the same config strategy w/ simple and it works and reports the correct version.

**Comment by scomoletti** [comment]
Ran into this issue as well. Aside from creating the dirs in advance I also had to change the DB_HOST var to 'linkace_db_1' since the linkace container was a different IP from mysql and the db port was not made accessible outside the container. Docker has internal dns on the default network based on service names within compose.yml so this works across restarts without needing to expose your db.

**Comment by mStirner** [comment]
Same here, fresh installation/docker setup.

`docker-compose.yml`
```yml
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:8081:80"
      #- "0.0.0.0:443:443"
    volumes:
      - ./.env:/app/.env
      - ./backups:/app/storage/app/backups
      - linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro

volumes:
  linkace_logs:
  db:
    driver: local
```

`.env`
```ini
## LINKACE CONFIGURATION

## Please note that the LinkAce Docker image will be renamed with the release of LinkAce 2!
## Read more: https://github.com/Kovah/LinkAce/issues/502

## Basic app configuration
COMPOSE_PROJECT_NAME=linkace
# The app key is generated later, please leave it like that
APP_KEY=aesah1daiw6Xot0IeP8bae5phiey3oaw

## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv, sqlite)
DB_CONNECTION=mysql
# Set the host of your database here
DB_HOST=db
# Set the port of your database here
DB_PORT=3306
# Set the database name here
DB_DATABASE=linkace
# Set both username and password of the user accessing the database
DB_USERNAME=linkace
# Wrap your password into quotes (") if it contains special characters
DB_PASSWORD=linkace

## Redis cache configuration
# Set the Redis connection here if you want to use it
REDIS_HOST=redis
REDIS_PASSWORD=ChangeThisToASecurePassword!
REDIS_PORT=6379
```
