### DISCUSSION TITLE
Error at database configuration

### DISCUSSION THREAD

**Discussion by Whoisfoxmulder** [Kovah/LinkAce#874] [Support] [answered]
Hi there,

I'm setting up LinkAce nearly successfully. However, at the database configuration step, an error appears:

`Please check your connection details. Details: SQLSTATE[HY000] [1045] Access denied for user 'linkace'@'172.21.0.1' (using password: YES) (Connection: setup, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'linkace' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)`

In the .env file, I set up the password (its linkace) for the database and I double-checked it. Any suggestions?

Thanks in advance <3

Here my configuration:

docker-compose.yml

```
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.5
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP 7.4 and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 49210:80
    volumes:
      - ./.env:/app/.env
      - linkace_logs:/app/storage/logs

volumes:
  linkace_logs:
  db:
    driver: local
```

.env

```
## LINKACE CONFIGURATION

## Basic app configuration
# The application name is used internally and may not be changed
APP_NAME=LinkAce
COMPOSE_PROJECT_NAME=linkace
# The URL should be set if you notice issues with URLs generated by Laravel, which might be an issue with
# nginx configuration or the proxy you use.
APP_URL=https://link.myurl.com
# The environment is usually 'production' but may be changed to 'local' for development
APP_ENV=production
# The app key is generated later, please leave it blank
APP_KEY=base64:BaQMjYHr226ZeKgfEApayMs9yaqJ+4yX7Wi+C+UzXAs=
# Enable the debug more if you are running into issues or while developing
APP_DEBUG=false
# Set to true, if you are using a proxy that terminates SSL. Required to get the correct URLs for LinkAce
FORCE_HTTPS=true
# Indicates that the setup was completed and the app can be used now
SETUP_COMPLETED=false
# Set the time after a session expires automatically, in minutes. Default is 7 days.
SESSION_LIFETIME=10080


## Backup configuration
# Enable backups here
BACKUP_ENABLED=false
# Choose the destination of the backup. If you set up AWS S3 credentials below you may choose 's3' which is used
# as a synonym for AWS. Leave blank or set to 'local' if you want to store backups within /storage/app/backups.
BACKUP_DISK=s3
# Set to false if you do not want to be notified about successful or broken backups
BACKUP_NOTIFICATIONS=true
# The notification email may be used to get backup notifications
BACKUP_NOTIFICATION_EMAIL=mymail@gmail.com
# Maximum size of all backups in megabytes
BACKUP_MAX_SIZE=512


## Amazon Web Services (AWS) S3 configuration
# Define the key ID, the access key, the region and your bucket name here if you want to use AWS S3 for backups
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=


## Mail configuration
MAIL_FROM_ADDRESS=mymail@gmail.com
MAIL_FROM_NAME=LinkAce
# Set the driver used for sending email here, default is `smtp`
MAIL_DRIVER=smtp
# Set the SMTP host and its port here
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
# Set the username used to connect to the SMTP server here
MAIL_USERNAME=mymail@gmail.com
# Set the password used to connect to the SMTP server here
MAIL_PASSWORD=mypw
# If your SMTP server uses encrypted connections, enable it here by setting the variable to `tls`
MAIL_ENCRYPTION=null


## Configuration of the database connection
## If you are using the standard configuration provided by LinkAce, you can leave all values except the password as
## they are. Docker will automatically create a linkace database and a corresponding user.
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=linkace
# Even if you use the standard configuration, please set a secure password here.
DB_USERNAME=linkace
DB_PASSWORD=linkace


## Redis cache configuration
# Set the Redis connection here if you want to use it
REDIS_HOST=redis
REDIS_PASSWORD=l9Sr*WnBYH8nx#
REDIS_PORT=6379


## You probably do not want to change any values blow. Only continue if you know what you are doing.
# Configure various driver
SESSION_DRIVER=file
LOG_CHANNEL=stack
BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_DRIVER=database

## Using Redis sockets
# If you want to use Redis via a Unix socket, you can remove the hash before the following lines, but remove one before
# the "CACHE_DRIVER" line above. Also, set a proper path to your Redis socket.
#CACHE_DRIVER=redis-socket
#SESSION_CONNECTION=redis-socket
#REDIS_SCHEME=unix
#REDIS_PATH=/path/to/redis.sock
```
