### DISCUSSION TITLE
LinkAce with Caddy on Arch Linux ARM

### DISCUSSION THREAD

**Discussion by RareBird15** [Kovah/LinkAce#924] [Support] [answered]
Hi all. I'm trying to get LinkAce going on my Raspberry Pi 500 running Arch Linux ARM, and I'm having some trouble. I'm hoping someone can help.
I'm trying to use LinkAce in Docker behind Caddy and Authelia, neither of which is in Docker. LinkAce seems to be starting its own Caddy instance, which worried me at first, but now I don't think that's the issue.
I'm getting 500 errors when trying to access LinkAce both locally and through Caddy. These are some of the logs I'm seeing:
```
2025-02-22 09:30:16,390 INFO supervisord started with pid 1
2025-02-22 09:30:17,394 INFO spawned: 'php-fpm' with pid 7
2025-02-22 09:30:17,396 INFO spawned: 'caddy' with pid 8
[22-Feb-2025 09:30:17] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[22-Feb-2025 09:30:17] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[22-Feb-2025 09:30:17] NOTICE: fpm is running, pid 7
[22-Feb-2025 09:30:17] NOTICE: ready to handle connections
{"level":"info","ts":1740216617.457752,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
{"level":"info","ts":1740216617.4593418,"msg":"adapted config to JSON","adapter":"caddyfile"}
{"level":"warn","ts":1740216617.4593587,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
{"level":"info","ts":1740216617.4606702,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1740216617.4609623,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x4000490a00"}
{"level":"warn","ts":1740216617.4609418,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"warn","ts":1740216617.4620528,"logger":"http","msg":"HTTP/2 skipped because it requires TLS","network":"tcp","addr":":80"}
{"level":"warn","ts":1740216617.462069,"logger":"http","msg":"HTTP/3 skipped because it requires TLS","network":"tcp","addr":":80"}
{"level":"info","ts":1740216617.4620733,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1740216617.4733706,"msg":"autosaved config (load with --resume flag)","file":"/home/www-data/.config/caddy/autosave.json"}
{"level":"info","ts":1740216617.4733975,"msg":"serving initial configuration"}
{"level":"info","ts":1740216617.4806514,"logger":"tls","msg":"cleaning storage unit","storage":"FileStorage:/home/www-data/.local/share/caddy"}
{"level":"info","ts":1740216617.485506,"logger":"tls","msg":"finished cleaning storage units"}
2025-02-22 09:30:18,487 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-02-22 09:30:18,487 INFO success: caddy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
::1 -  22/Feb/2025:09:30:32 +0000 "GET /index.php" 500
::1 -  22/Feb/2025:09:30:32 +0000 "GET /index.php" 500
::1 -  22/Feb/2025:09:30:32 +0000 "GET /index.php" 500
::1 -  22/Feb/2025:09:30:33 +0000 "GET /index.php" 500
```
My Docker-Compose file looks like:
```
services:
  # --- LinkAce
  linkace:
    image: docker.io/linkace/linkace:latest
    container_name: linkace
    restart: unless-stopped
    depends_on:
      - linkace_db
    ports:
      - "0.0.0.0:3009:80"
    volumes:
      - ./.env:/app/.env
      - ./backups:/app/storage/app/backups

  # --- Database
  linkace_db:
    image: docker.io/library/mariadb:11.5
    container_name: linkace_db
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- Cache
  linkace_redis:
    image: docker.io/bitnami/redis:7.4
    container_name: linkace_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  db:
```
I've defined all relevant variables in my .env file.
Can anyone help me figure out how to fix this? Thanks.
