### DISCUSSION TITLE
LinkAce with Caddy on Arch Linux ARM: Browser says forms are not secure, curl shows HTTPS to HTTP redirects

### DISCUSSION THREAD

**Discussion by RareBird15** [Kovah/LinkAce#935] [Support]
### Describe your issue

This isn't a huge deal because LinkAce is usable, but it is somewhat annoying, and I'd like to see if it can be fixed. For every form, whether it's the login form or the form to add a link, my browser says this form is not secure. I've tried a variety of changes in both Caddy and my LinkAce .env file with no luck. Can anyone help?

## Caddyfile

```
{
    admin 127.0.0.1:2019 {
        origins localhost 127.0.0.1 caddy.laniecarmelo.tech
    }
    debug
    http_port 80
    https_port 443
}

# Project Demos
demos.laniecarmelo.tech {
    # Redirect root to portfolio
    handle / {
        redir https://laniecarmelo.tech/accessible-programming-portfolio/ 301
    }

    # Serve project directories
    handle /* {
        root * /var/www/demos
        file_server {
            hide .git
            index index.html
        }
        try_files {path} {path}/ /index.html
    }

    # Inherit global security headers
    header {
        Content-Security-Policy "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; form-action 'self'; frame-ancestors 'self'"
        Referrer-Policy "strict-origin-when-cross-origin"
    }
    encode br gzip
}

*.laniecarmelo.tech {
    tls laniecarmelo@gmail.com {
        dns cloudflare redacted
    }
    
    header {
        Content-Security-Policy "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src https: data:; frame-src 'self' https:; object-src 'none'"
        Referrer-Policy "strict-origin-when-cross-origin"
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options "nosniff"
        X-Xss-Protection "1; mode=block"
    }

    encode br gzip

    # Home
    @home host home.laniecarmelo.tech
    handle @home {
        reverse_proxy 127.0.0.1:3000
    }

    # Read
    @read host read.laniecarmelo.tech
    handle @read {
        reverse_proxy 127.0.0.1:8000
    }

    # Bookmarks
    @bookmarks host bookmarks.laniecarmelo.tech
    handle @bookmarks {
        reverse_proxy 127.0.0.1:3009 {
            header_up Host {host}
            header_up X-Forwarded-Port 443
        }
    
        # Override global headers
        header {
            Content-Security-Policy "default-src 'self' https: data: 'unsafe-inline'"
            Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        }
    }

    # RSS
    @rss host rss.laniecarmelo.tech
    handle @rss {
        reverse_proxy 127.0.0.1:3010
    }

    # RSS Bridge
    @rssbridge host rss-bridge.laniecarmelo.tech
    handle @rssbridge {
        reverse_proxy 127.0.0.1:3015
    }

    # Miniflux AI
    @miniflux host miniflux-ai.laniecarmelo.tech
    handle @miniflux {
        reverse_proxy 127.0.0.1:8083
    }

    # n8n
    @n8n host n8n.laniecarmelo.tech
    handle @n8n {
        reverse_proxy 127.0.0.1:5678
    }

    # Files
    @files host files.laniecarmelo.tech
    handle @files {
        reverse_proxy 127.0.0.1:3007
    }

    # Todo
    @todo host todo.laniecarmelo.tech
    handle @todo {
        reverse_proxy 127.0.0.1:3456
    }

    # Caddy
    @caddy host caddy.laniecarmelo.tech
    handle @caddy {
        reverse_proxy 127.0.0.1:2019
    }

    # AdGuard
    @adguard host adguard.laniecarmelo.tech
    handle @adguard {
        reverse_proxy 127.0.0.1:3001
    }

    # Recipes
    @recipes host recipes.laniecarmelo.tech
    handle @recipes {
        reverse_proxy 127.0.0.1:8081
    }

    # Dockge
    @dockge host dockge.laniecarmelo.tech
    handle @dockge {
        reverse_proxy 127.0.0.1:5001
    }

    # Dozzle
    @dozzle host dozzle.laniecarmelo.tech
    handle @dozzle {
        reverse_proxy 127.0.0.1:8080
    }

    # Uptime
    @uptime host uptime.laniecarmelo.tech
    handle @uptime {
        reverse_proxy 127.0.0.1:3006
    }

    # Beszel
    @beszel host beszel.laniecarmelo.tech
    handle @beszel {
        reverse_proxy 127.0.0.1:8090
    }

    # Code
    @code host code.laniecarmelo.tech
    handle @code {
        reverse_proxy 127.0.0.1:3012
    }

    # Notes
    @notes host notes.laniecarmelo.tech
    handle @notes {
        reverse_proxy 127.0.0.1:5000
    }

    # Git
    @git host git.laniecarmelo.tech
    handle @git {
        reverse_proxy 127.0.0.1:3008
    }

    # IRC
    @irc host irc.laniecarmelo.tech
    handle @irc {
        reverse_proxy 127.0.0.1:3011
    }

    # Search
    @search host search.laniecarmelo.tech
    handle @search {
        reverse_proxy 127.0.0.1:8082
    }

    # AI
    @ai host ai.laniecarmelo.tech
    handle @ai {
        reverse_proxy 127.0.0.1:3080
    }

    # Cockpit
    @cockpit host cockpit.laniecarmelo.tech
    handle @cockpit {
        reverse_proxy 127.0.0.1:3004
    }

    # PrivateBin
    @paste host paste.laniecarmelo.tech
handle @paste {
    reverse_proxy localhost:8085 {
        header_up X-Real-IP {remote_host}
    }
}

    # Shlink
    @links host links.laniecarmelo.tech
    handle @links {
        reverse_proxy 127.0.0.1:8084
    }

    # Catch-all for undefined subdomains
    handle {
        respond "Not Found" 404
    }
}
```

## Docker compose file:

```
services:
  linkace:
    image: docker.io/linkace/linkace:latest
    container_name: linkace
    restart: unless-stopped
    environment:
      - APP_URL=https://bookmarks.laniecarmelo.tech
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=linkace_db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=linkace_redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - APP_DEBUG=${APP_DEBUG}
      - REGULAR_LOGIN_DISABLED=${REGULAR_LOGIN_DISABLED}
      - TRUSTED_PROXIES=*
      - FORCE_HTTPS=true
      - LINKACE_DOMAIN=${LINKACE_DOMAIN}
    depends_on:
      - linkace_db
      - linkace_redis
    ports:
      - 0.0.0.0:3009:80
    volumes:
      - /opt/stacks/linkace/backups:/var/www/html/storage/app/backups
      - /opt/stacks/linkace/public:/var/www/html/public
  linkace_db:
    image: docker.io/library/mariadb:11.5
    container_name: linkace_db
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql
  linkace_redis:
    image: docker.io/bitnami/redis:7.4
    container_name: linkace_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
volumes:
  db: null
networks: {}
```

## .env file

```
APP_KEY=redacted
APP_ENV=production
TRUSTED_PROXIES=172.80.1.0/24,10.0.0.0/8,192.168.0.0/16  # COMMA-SEPARATED
APP_URL=https://bookmarks.laniecarmelo.tech
FORCE_HTTPS=true
SESSION_SECURE_COOKIE=true
DB_CONNECTION=mysql
DB_HOST=linkace_db
DB_PORT=3306
DB_DATABASE=linkace
DB_USERNAME=linkace
DB_PASSWORD=redacted
REDIS_HOST=linkace_redis
REDIS_PASSWORD=redacted
REDIS_PORT=6379
APP_DEBUG=true
REGULAR_LOGIN_DISABLED=false
LINKACE_DOMAIN=bookmarks.laniecarmelo.tech
MAIL_FROM_ADDRESS=linkace@laniecarmelo.tech
MAIL_FROM_NAME=LinkAce
# Set the driver used for sending email here, default is `log`
MAIL_MAILER=smtp
# Set the SMTP host and its port here
MAIL_HOST=smtp.zeptomail.com
MAIL_PORT=587
# Set the username used to connect to the SMTP server here
MAIL_USERNAME=emailapikey
# Set the password used to connect to the SMTP server here
MAIL_PASSWORD='redacted'
# If your SMTP server uses encrypted connections, enable it here by setting the variable to `tls`
MAIL_ENCRYPTION=tls
```

I'm also still experiencing the problem with not being able to check for updates. Does anyone know what might cause all this and how I can fix it? Thanks.

### Troubleshooting Steps

- [x] I have read the troubleshooting guide
- [x] I have searched the community discussions for similar issues
