### DISCUSSION TITLE
An error occurs when running the.env MySQL configuration.

### DISCUSSION THREAD

**Discussion by ZhaoHf666** [Kovah/LinkAce#947] [Support]
### Describe your issue

```
Database could not be configured. Please check your connection details. Details: The command "mysql --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" failed. Exit Code: 1(General error) Working directory: /app/public Output: ================ Error Output: ================ mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead ERROR 2026 (HY000): TLS/SSL error: self-signed certificate in certificate chain
```

my compose
```yml
services:
  linkAce:
    image: docker.io/linkace/linkace:latest
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./.env:/app/.env
      - E:/Docker Desktop/LinkAce/backups:/app/storage/app/backups
```

.env
```env
DB_CONNECTION=mysql
DB_HOST=101.111.111.111
DB_PORT=3306
DB_DATABASE=linkace
DB_USERNAME=zhfnb
DB_PASSWORD=12345678
```

### Troubleshooting Steps

- [X] I have read the troubleshooting guide
- [X] I have searched the community discussions for similar issues
