### DISCUSSION TITLE
Getting `500 - Server Error` after installing with docker

### DISCUSSION THREAD

**Discussion by r00bit1984** [Kovah/LinkAce#969] [Support]
### Describe your issue

<img width="1146" alt="SCR-20250607-qwus" src="https://github.com/user-attachments/assets/63366e1d-b28a-4a49-a753-34d5be906965" />

I tried running the commands listed in the wiki to get the server up and running without a GUI but it didnt help either:
```
docker exec -it linkace_app_1 php artisan migrate
docker exec -it linkace_app_1 php artisan setup:complete
docker exec -it linkace_app_1 php artisan registeruser --admin
```

Here's my `docker-compose.yaml`:
```
services:
  # --- LinkAce
  app:
    image: docker.io/linkace/linkace:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:1112:80"
      # Remove the hash of the following line if you want to use HTTPS for this container
      #- "0.0.0.0:443:443"
    volumes:
      - ./.env:/app/.env
      #- ./backups:/app/storage/app/backups
      # Remove the hash of the following lines if you want to use HTTPS for this container
      #- ./caddy-data:/home/www-data/.local/share/caddy
      #- ./ssl.Caddyfile:/etc/caddy/Caddyfile

  # --- Database
  db:
    image: docker.io/library/mariadb:11.5
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- Cache
  redis:
    image: docker.io/bitnami/redis:7.4
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  db:
```
**Relevant Logs:**
- `DB Container`: https://pastes.dev/bzD5vI37od
- `App Container`: https://pastes.dev/gpPAyozezy
- `Redis Container`: https://pastes.dev/8foN4GJWYs

Any Help is very appreciated

### Troubleshooting Steps

- [X] I have read the troubleshooting guide
- [X] I have searched the community discussions for similar issues
