### ISSUE TITLE
KEY creation failure

### ISSUE THREAD

**Issue by kelserj** [Kovah/LinkAce#130]
Execute:   

      Mac:LinkAce Admin$ docker exec -it linkace_php_1  bash -c "php artisan key:generate"

Returns:  

    In KeyGenerateCommand.php line 96:
                                                                              
    file_put_contents(/app/.env): failed to open stream: Read-only file system  
                                                                              
The version in the xml file is: version: "3"
Image on docker was latest - above 0.0.35

I have tried to log in and run the command on the docker. A whole lot of searching for the error code and possible work arounds. I have changed permissions. What I cannot find is where the script is located that is running that had line 96 in it. I __did not__ do the optional ssl configuration. 

Thanks - Appreciate your work and look forward to using it. 

On a mac osx 10.15.4

John

**Comment by Kovah** [comment]
Please try changing the docker-compose file.  Replace
```yaml
  # --- LinkAce Image with PHP 7.4
  php:
    image: linkace/linkace:latest
    restart: always
    volumes:
      - linkace_app:/app
      - ./.env:/app/.env:ro
```
with
```yaml
  # --- LinkAce Image with PHP 7.4
  php:
    image: linkace/linkace:latest
    restart: always
    volumes:
      - linkace_app:/app
      - ./.env:/app/.env
```
(last line is important)

Thanks for the hint, will example files be corrected in the next release.
