### ISSUE TITLE
Docker bind mounts permission issue

### ISSUE THREAD

**Issue by frumpymoons** [Kovah/LinkAce#207]
Using a bind mount instead of a volume can result in a permission issue unless the UID/GID on the host is 1000.
Example config:
```yaml
  linkace:
    image: linkace/linkace:php-nginx
    container_name: linkace
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - proxy
      - internal
    volumes:
      - $DOCKERDIR/linkace/.env:/app/.env
      - $DOCKERDIR/linkace/nginx-simple.conf:/opt/docker/etc/nginx/conf.d/linkace.conf:ro
      - $DOCKERDIR/linkace/logs:/app/storage/logs
      - $DOCKERDIR/linkace/backups:/app/storage/app/backups
    labels:
      traefik.enable: true
      traefik.http.routers.linkace.entrypoints: web-secure
      traefik.http.routers.linkace.rule: Host(`linkace.$DOMAINNAME`)
      traefik.http.routers.linkace.service: linkace
      traefik.http.services.linkace.loadbalancer.server.port: 80
```
These two mounts have root permissions per default. The application user inside the container is unable to write.
The requirement check for "/storage and /storage/logs directories are writable" fails.
```yaml
      - $DOCKERDIR/linkace/logs:/app/storage/logs
      - $DOCKERDIR/linkace/backups:/app/storage/app/backups
```

Would it be possible to change the UID/GID via docker environment variables? So that these directories and the application user have the same UID/GID.
