### ISSUE TITLE
Allow Docker env vars in place of linking an .env file

### ISSUE THREAD

**Issue by bachya** [Kovah/LinkAce#232]
**Is your feature request related to a problem? Please describe.**
It is common practice to provide environment variables to Docker containers via runtime environment variables (instead of mounting/copying an `.env` file into the container). LinkAce should support this. If an actual `.env` file isn't found, LinkeAce won't start:

![Screen Shot 2021-02-10 at 12 06 02 PM](https://user-images.githubusercontent.com/47216/107558727-61815900-6b98-11eb-9f1a-44dc83e8ce0c.png)

**Describe the solution you'd like**
I would like to be able to provide values specified by the `.env` files using Docker mechanisms. For instance, a `docker-compose.yml` might look like this:

```yaml
linkace:
  container_name: linkace
  environment:
    APP_DEBUG: "true"
    APP_URL: "https://${TRAEFIK_HOST_LINKACE}:{TRAEFIK_PORT}"
    DB_DATABASE: "${LINKACE_DB_NAME}"
    DB_HOST: linkace-db
    DB_PASSWORD: "${LINKACE_DB_PASSWORD}"
    DB_USERNAME: "${LINKACE_DB_USER}"
    REDIS_HOST: linkace-redis
    REDIS_PASSWORD: "${LINKACE_REDIS_PASSWORD}"
  image: "linkace/linkace:${LINKACE_VERSION}-php-nginx"
  restart: always
  volumes:
    linkace-data:/app
```

**Describe alternatives you've considered**
The supported method – mounting/copying an `.env` file into the container – is the alternative, I suppose.
