### ISSUE TITLE
Error 500 after update-docker.sh

### ISSUE THREAD

**Issue by adrianmihalko** [Kovah/LinkAce#259]
**Describe the bug**

I wanted to upgrade my LinkAce installation with update-docker.sh, but after running it I am now getting 500 error.

<img width="1213" alt="Screenshot 2021-04-09 at 19 47 25" src="https://user-images.githubusercontent.com/733361/114221319-78acaf00-996d-11eb-8105-89aa5d9b8499.png">

```
The LinkAce image was successfully updated.

You should upgrade the database now. Should the script take care of it? [y/n] y
> Migrating database...
ERROR: No such service: php

LinkAce was upgraded successfully!

Should the configuration and routes be cached now? This might improve overall performance. [y/n] y
ERROR: No such service: php
ERROR: No such service: php

Thanks for using LinkAce! :)
madrian@debian:~/docker/linkace$
madrian@debian:~/docker/linkace$ nano docker-compose.yml
madrian@debian:~/docker/linkace$ sudo docker-compose run php php artisan migrate
ERROR: No such service: php
madrian@debian:~/docker/linkace$

```
**To Reproduce**

**Expected behavior**

**Screenshots**

**LinkAce setup (please complete the following information):**
 - Version: [e.g. 0.0.43]
 - Installed via: [e.g. PHP, Docker]
 - OS: [e.g. Ubuntu, CentOS, Windows]

**Desktop (please complete the following information if applicable):**

**Smartphone (please complete the following information if applicable):**

**Additional context**

**Comment by adrianmihalko** [comment]
My docker-compose.yml:

```
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.5
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/bitnami

  # --- LinkAce Image with PHP 7.4 and nginx
  app:
    image: linkace/linkace:php-nginx
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:8888:8080"
      #- "0.0.0.0:443:8443"
    volumes:
      - ./.env:/app/.env
      - ./nginx-simple.conf:/opt/docker/etc/nginx/conf.d/linkace.conf:ro
      - linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use local backups
      #- ./backups:/app/storage/app/backups
      # Remove the hash of the following line if you are using HTTPS
      #- /path/to/your/ssl/certificates:/opt/docker/etc/nginx/ssl

volumes:
  linkace_logs:
  db:
    driver: local
```
