### ISSUE TITLE
Database could not be configured

### ISSUE THREAD

**Issue by aashish108** [Kovah/LinkAce#423]
Hey there. I get this error during setup (https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced/). Any help much appreciated! Everything is configured correctly as far as I can see.

```
Database could not be configured. Please check your connection details. Details: SQLSTATE[HY000] [2002] Connection refused (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')
```

This is the db section in my compose file:

```
  linkace-db:
    container_name: linkace-db
    image: linuxserver/mariadb:10.5.15
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --user=root --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - PUID=911
      - PGID=911
      - MYSQL_ROOT_PASSWORD=${LINKACE_ROOT_DB_PASSWORD}
      - MYSQL_USER=${LINKACE_DB_USER}
      - MYSQL_PASSWORD=${LINKACE_DB_PASSWORD}
      - MYSQL_DATABASE=${LINKACE_DB_NAME}
      - TZ=Europe/London
    ports:
      - ${LINKACE_DB_PORT}:3306
    volumes:
      - ${LINKACE_DB_VOLUME}:/var/lib/mysql:shared
      - ${LINKACE_DB_VOLUME}/backup:/var/lib/backup:shared
    networks:
      - linkace-net
```

Compose .env vars:

```
LINKACE_ROOT_DB_PASSWORD=loqwa3rt9ijh78qa
LINKACE_DB_USER=linkace
LINKACE_DB_PASSWORD=qsdp09ij763edf54
LINKACE_DB_NAME=linkace
LINKACE_DB_VOLUME=/mnt/share/Cloud/linkace/db
LINKACE_DB_PORT=3309
LINKACE_APP=/mnt/share/Cloud/linkace/app
LINKACE_LOGS=/mnt/share/Cloud/linkace/logs
LINKACE_REDIS_PASSWORD=23edsapo98uy
LINKACE_PORT=8389
LINKACE_ENV=/mnt/share/Cloud/linkace/env
```

And here's my Linkace .env:

```
## LINKACE CONFIGURATION

APP_NAME=LinkAce
COMPOSE_PROJECT_NAME=linkace
APP_URL=redacted
APP_ENV=production
APP_KEY=
APP_DEBUG=false
SETUP_COMPLETED=false
SESSION_LIFETIME=10080

DB_CONNECTION=mysql
DB_HOST=linkace-db
DB_PORT=3309
DB_DATABASE=linkace
DB_USERNAME=linkace
DB_PASSWORD=qsdp09ij763edf54

REDIS_HOST=linkace-redis
# REDIS_PASSWORD=23edsapo98uy
REDIS_PASSWORD=
REDIS_PORT=6379

SESSION_DRIVER=redis
LOG_CHANNEL=stack
BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_DRIVER=database
```
