### ISSUE TITLE
Installed exactly as documented, but ended up with an error when initialized in the web page

### ISSUE THREAD

**Issue by ZevaXu** [Kovah/LinkAce#462]
### Describe the bug
```Database could not be configured. Please check your connection details. Details: SQLSTATE[HY000] [1045] Access denied for user 'linkace'@'172.20.0.3' (using password: YES) (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')```

![20220427-2127-CSBBeb](https://cdn.jsdelivr.net/gh/ZevaXu/picupload@master/uPic/20220427-2127-CSBBeb.png)

![20220427-2123-tcjWCJ](https://cdn.jsdelivr.net/gh/ZevaXu/picupload@master/uPic/20220427-2123-tcjWCJ.png)
### log:
```
db_1   | 2022-04-27 13:22:32+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.3+maria~focal started.
db_1   | 2022-04-27 13:22:32+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1   | 2022-04-27 13:22:32+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.3+maria~focal started.
db_1   | 2022-04-27 13:22:33+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
db_1   | 2022-04-27 13:22:33 0 [Note] mysqld (server 10.7.3-MariaDB-1:10.7.3+maria~focal) starting as process 1 ...
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Number of transaction pools: 1
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Using ARMv8 crc32 + pmull instructions
db_1   | 2022-04-27 13:22:33 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Using Linux native AIO
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Completed initialization of buffer pool
app_1  | 2022-04-27 13:22:33,336 INFO Set uid to user 0 succeeded
app_1  | 2022-04-27 13:22:33,338 INFO supervisord started with pid 1
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: 128 rollback segments are active.
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: 10.7.3 started; log sequence number 476963; transaction id 712
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1   | 2022-04-27 13:22:33 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1   | 2022-04-27 13:22:33 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
db_1   | 2022-04-27 13:22:33 0 [Note] Server socket created on IP: '0.0.0.0'.
db_1   | 2022-04-27 13:22:33 0 [Note] Server socket created on IP: '::'.
db_1   | 2022-04-27 13:22:33 0 [Note] mysqld: ready for connections.
db_1   | Version: '10.7.3-MariaDB-1:10.7.3+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
db_1   | 2022-04-27 13:22:33 0 [Note] InnoDB: Buffer pool(s) load completed at 220427 13:22:33
app_1  | 2022-04-27 13:22:34,341 INFO spawned: 'php-fpm' with pid 7
app_1  | 2022-04-27 13:22:34,343 INFO spawned: 'nginx' with pid 8
app_1  | [27-Apr-2022 13:22:34] NOTICE: fpm is running, pid 7
app_1  | [27-Apr-2022 13:22:34] NOTICE: ready to handle connections
app_1  | 2022-04-27 13:22:35,368 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1  | 2022-04-27 13:22:35,369 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
db_1   | 2022-04-27 13:22:43 3 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
db_1   | 2022-04-27 13:22:43 4 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
app_1  | 127.0.0.1 -  27/Apr/2022:13:22:43 +0000 "GET /index.php" 200
app_1  | 172.20.0.1 - - [27/Apr/2022:13:22:43 +0000] "GET /setup/requirements HTTP/1.1" 200 2957 "https://my_doman/setup/start" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15" "my_ip"
db_1   | 2022-04-27 13:22:45 5 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
db_1   | 2022-04-27 13:22:45 6 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
app_1  | 127.0.0.1 -  27/Apr/2022:13:22:45 +0000 "GET /index.php" 200
app_1  | 172.20.0.1 - - [27/Apr/2022:13:22:45 +0000] "GET /setup/database HTTP/1.1" 200 3105 "my_doman/setup/requirements" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15" "my_ip"
db_1   | 2022-04-27 13:22:48 7 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
db_1   | 2022-04-27 13:22:48 8 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
db_1   | 2022-04-27 13:22:48 9 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
db_1   | 2022-04-27 13:22:48 10 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
app_1  | 172.20.0.1 - - [27/Apr/2022:13:22:48 +0000] "POST /setup/database HTTP/1.1" 302 418 "https://my_doman/setup/database" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15" "ip"
app_1  | 127.0.0.1 -  27/Apr/2022:13:22:48 +0000 "POST /index.php" 302
db_1   | 2022-04-27 13:22:48 11 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
db_1   | 2022-04-27 13:22:48 12 [Warning] Access denied for user 'linkace'@'172.20.0.3' (using password: YES)
app_1  | 127.0.0.1 -  27/Apr/2022:13:22:48 +0000 "GET /index.php" 200
app_1  | 172.20.0.1 - - [27/Apr/2022:13:22:48 +0000] "GET /setup/database HTTP/1.1" 200 3299 "https://my_doman/setup/database" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15" "ip"
```

###  the .env file:
```
## LINKACE CONFIGURATION

## Basic app configuration
COMPOSE_PROJECT_NAME=linkace
# The app key is generated later, please leave it blank
APP_KEY=base64:YvPN9nU60PUyCG5pGL2TATBJdBv66Wyrh5/DCe4ynkU=

## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv)
DB_CONNECTION=mysql
# Set the host of your database here
DB_HOST=db
# Set the port of your database here
DB_PORT=3306
# Set the database name here
DB_DATABASE=linkace
# Set both username and password of the user accessing the database
DB_USERNAME=linkace
DB_PASSWORD=iSNkZ3CtPuud7nUgGq3CBi3Ze

## Redis cache configuration
# Set the Redis connection here if you want to use it
REDIS_HOST=redis
REDIS_PASSWORD=iSNkZ3CtPuud7nUgGq3CBi3Ze
REDIS_PORT=6379
```

### the docker-compose.yml file
```
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:2143:80"
      #- "0.0.0.0:443:443"
    volumes:
      - ./.env:/app/.env
      - linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro
      # Remove the hash of the following line if you want to use local backups
      #- ./backups:/app/storage/app/backups


volumes:
  linkace_logs:
  db:
    driver: local
```

**Comment by matthewblott** [comment]
I have the same issue

**Comment by matthewblott** [comment]
Okay I've played around with this for a couple of hours and found what works for me. I'm using Portainer but a simple `docker-compose` command will work much the same. My `docker-compose` file:

```
version: '3'
services:
  db:
    image: mariadb:10.7
    container_name: linkace_db
    #network_mode: bridge
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=linkace
      - MYSQL_USER=linkace_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /home/deployer/docker/linkace/data/db:/var/lib/mysql
  app:
    image: linkace/linkace:simple
    container_name: linkace
    #network_mode: bridge
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8007:80'
    environment:
      - APP_KEY=${APP_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SETUP_COMPLETED=false
    volumes:
      - /path/to/container/.env:/app/.env
      - logs:/app/storage/logs
volumes:
  logs:
```

I then added variables in Portainer but you can add them to the `.env` file or directly in the compose file. If you use Portainer (or any method) you absolutely require the `.env` file with the correct permissions:

```
touch .env
chmod 666 .env
```

One other gotcha is to make sure the `data` file is clear. I ran the following before any `docker-compose` command:

```
sudo rm -rf data && mkdir data
```

I hope this helps anyone else 🙂

**Comment by Kovah** [comment]
If might help if you delete the volume of the MySQL / MariaDB container.

**Comment by ZevaXu** [comment]
Thanks @matthewblott @Kovah! It finally works fine.
I'm posting my setup steps here:
1. If your linkace_app is still running, stop it `docker-compose down`
2. delete the useless volumes `docker volume prune`  
3. edit the ./env file and set the permissions of it `chmod 666 ./env`
```
## LINKACE CONFIGURATION

## Basic app configuration
COMPOSE_PROJECT_NAME=linkace
# The app key is generated later, please leave it blank
APP_KEY=base64:YvPN9nU60PUyCG5pGL2TATBJdBv66Wyrh5/DCe4ynkU=

## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv)
DB_CONNECTION=mysql
# Set the host of your database here
DB_HOST=db
# Set the port of your database here
DB_PORT=3306
# Set the database name here
DB_DATABASE=linkace
# Set both username and password of the user accessing the database
DB_USERNAME=linkace
DB_PASSWORD=your_passwd

## Redis cache configuration
# Set the Redis connection here if you want to use it
REDIS_HOST=redis
REDIS_PASSWORD=your_passwd
REDIS_PORT=6379
```
4. edit the docker-compose.yml file (according to @matthewblott posted above but a little change )
```
version: '3'
services:
  db:
    image: mariadb:10.7
    container_name: linkace_db
    #network_mode: bridge
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
  app:
    image: linkace/linkace:simple
    container_name: linkace
    #network_mode: bridge
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8001:80'
    environment:
      - APP_KEY=${APP_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SETUP_COMPLETED=false
    volumes:
      - /home/ubuntu/DockerApp/Linkace/.env:/app/.env
      - logs:/app/storage/logs
volumes:
  logs:

```
5. If there is any data generated by the old container run, clear it(important), `rm -rf <database_volume_path>`. for me, the command is `rm -rf /home/ubuntu/DockerApp/Linkace/data` .
6. finally `docker-copose up -d` it
