### ISSUE TITLE
Make `.env` being writable optional when configuring via environment variables

### ISSUE THREAD

**Issue by schnerring** [Kovah/LinkAce#499]
**Is your feature request related to a problem? Please describe.**

The Linkace setup process requires `.env` to be writable during first time setup. In the TrueCharts app repo we implemented a Linkace Helm chart that allows TrueNAS SCALE users to easily deploy Linkace with a few clicks.

The Helm chart uses only environment variables to configure Linkace. However, the first-time-setup process requires `.env` to be writable by the `www-data` user.

The user needs to connect to the container via shell, `chmod a+w /app/.env`, and then finish the setup. The DB connection is actually written to `.env` but discarded the next time the container restarts.

**Describe the solution you'd like**

When configuration via environment variables is sufficient, `/app/.env` being writable should be optional.

**Describe alternatives you've considered**

[Fix (more of a hack) the issue by modifying the Docker image like this](https://github.com/truecharts/containers):

```Dockerfile
FROM linkace/linkace:v1.10.2-simple@sha256:3f6b38b698b8792d37b2ba90953deefbc9159d44e27344dd78b4b2f65faa6185
RUN chmod a+w /app/.env
```

**Comment by Kovah** [comment]
Hey, thanks for the input!
Technically, the .env file is not really needed to setup LinkAce, it just needs to be configured correctly. See https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced-configuration/ for more details.
But I'll see what I can do to improve the setup process and make it more clear and easy to use.

**Comment by schnerring** [comment]
> it just needs to be configured correctly.

We're not mounting any custom `.env` file, it's just the [default one included in the Docker image](https://github.com/Kovah/LinkAce/blob/main/resources/docker/dockerfiles/release-multiplatform.Dockerfile#L18):

The file is part of root filesystem and owned by root:

```text

```

**Comment by Kovah** [comment]
I'll see if I can update the setup documentation. It is possible to configure LinkAce without the built in setup, which also does not need the env file being writable.

**Comment by stavros-k** [comment]
It's not just about documentation. The included `.env` file in the container needs to have the correct default permissions.
Currently it's owned by `root`. But the preflight check is done by user `www-data` if I'm not wrong

This is the preflight check of the container without mounting a `.env` file. 
![image](https://user-images.githubusercontent.com/47820033/177031816-c6fefdca-cd28-4f57-97c5-3ce7a7b64535.png)

Required env's are defined 
https://github.com/truecharts/apps/blob/aa51656f2b966d1d1399dd0120c951622eefb68d/charts/stable/linkace/values.yaml#L30-L68

**Comment by AlexKalopsia** [comment]
I am having the same issue. `.env` is owned by `root`, and I still get that fail. Should I change to something specific?

**Comment by Kovah** [comment]
For the setup process it should be enough to make the file read and writable by others (0766) and then switch it back after that.

**Comment by AlexKalopsia** [comment]
This still doesn't work for me, perhaps it's because I have a different folder setup. 
My `docker-compose.yaml` is in `${DOCKER_PATH}` , and in `${DOCKER_PATH}` I have `.env` as well as a `linkace/` folder (where I wanna mount the volumes. 
My `docker-compose` looks like this

```
linkace:
    image: linkace/linkace:simple
    container_name: linkace
    depends_on:
      - mariadb
    environment:
      - APP_KEY=${LINKACE_API}
      - DB_CONNECTION=mysql
      - DB_HOST=${IP}
      - DB_DATABASE=${LINKACE_DB}
      - DB_USERNAME=${LINKACE_USER}
      - DB_PASSWORD=${LINKACE_PSW}
      - COMPOSE_PROJECT_NAME=linkace
    ports:
      - "0.0.0.0:7788:80"
    volumes:
      - ${DOCKER_PATH}/linkace/linkace_logs:/app/storage/logs
      - ${DOCKER_PATH}/linkace/backups:/app/storage/app/backups
    restart: unless-stopped
```

I gave 0766 to `.env` or even `0777`, but LinkAce still says it can't be written to. I have also tried to have a separate `.env` file in `${DOCKER_PATH}/linkace/` with 0766, but that didn't work either
