### ISSUE TITLE
I can't get into the dashboard after I finish built-in setup.

### ISSUE THREAD

**Issue by xiqoqi** [Kovah/LinkAce#517]
**Describe the bug**

I can't get into the dashboard after I finish built-in setup.

**To Reproduce**

All the steps and logs are here.
http://152.70.83.140/20220722012421.mp4

**Expected behavior**

I just want it to get back to normal.

**LinkAce setup (please complete the following information):**
 - Version: [1.10.2]
 - Installed via: [ Docker]
 - OS: [CentOS]

**Desktop (please complete the following information if applicable):**
 - OS: [windows]
 - Browser [chrome, edge,and firefox]
 - Version [ i dont know]

**Additional context**

I built it according to https://www.linkace.org/docs/v1/setup/setup-with-docker/advanced.

**This is my .env file.**

```

## LINKACE CONFIGURATION
APP_DEBUG=true
## Basic app configuration
COMPOSE_PROJECT_NAME=linkace
# The app key is generated later, please leave it blank
APP_KEY=zFiU8Hg4KtkNC5XjQ6DFNMmU2GQg4x9c

## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv)
DB_CONNECTION=mysql
# Set the host of your database here
DB_HOST=db
# Set the port of your database here
DB_PORT=3306
# Set the database name here
DB_DATABASE=linkace
# Set both username and password of the user accessing the database
DB_USERNAME=linkace
DB_PASSWORD=linkace

## Redis cache configuration
# Set the Redis connection here if you want to use it
REDIS_HOST=redis
REDIS_PASSWORD=linkace
REDIS_PORT=6379

SESSION_DRIVER=redis
CACHE_DRIVER=redis

```

**This is my docker-compose.yml file.**

```
version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP
  app:
    image: linkace/linkace:latest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
      - linkace_app:/app
      - linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use local backups
      #- ./backups:/app/storage/app/backups

  # --- nginx
  nginx:
    image: bitnami/nginx:1.21
    restart: unless-stopped
    ports:
      - "0.0.0.0:12424:8080"
      #- "0.0.0.0:443:8443"
    depends_on:
      - app
    volumes:
      - linkace_app:/app
      # Replace `nginx.conf` with `nginx-ssl.conf` and remove the hash from the following line
      # if you want to use HTTPS for this container
      - ./nginx.conf:/opt/bitnami/nginx/conf/server_blocks/linkace.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro

  # --- Redis
  redis:
    image: bitnami/redis:6.2
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  linkace_app:
  linkace_logs:
  db:
    driver: local
```

**This is my nginx.conf file.**

```
server {
    root /app/public;
    server_name _;
    index index.php;
    charset utf-8;
    client_max_body_size 20M;
    port_in_redirect off;

    # Choose the connection method
    listen 0.0.0.0:8080;

    # Content security headers for Laravel
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_comp_level 8;
    gzip_min_length 256;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types application/javascript application/x-javascript application/xhtml+xml font/woff font/woff2 image/svg+xml image/x-icon text/css text/javascript text/plain text/xml;

    # Location configs
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Assets and media files
    location ~* \.(?:css|js|map|scss|jpg|jpeg|png|avif|gif|mp4|woff|woff2|ico|svg|webmanifest)$ {
      expires max;
      access_log off;
      add_header Cache-Control "public";
      try_files $uri =404;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Error pages
    error_page 404 /index.php;
    error_page 403 /index.php;

    # PHP handling
    location ~ \.php$ {
        fastcgi_pass app:9000;

        try_files $uri /index.php;
        include fastcgi.conf;
        fastcgi_keep_conn on;
        fastcgi_intercept_errors on;
        fastcgi_index index.php;
        fastcgi_read_timeout 300;
    }
}
```
