### ISSUE TITLE
HTTP 500 on setup + no logs

### ISSUE THREAD

**Issue by black-backdoor** [Kovah/LinkAce#735]
### Bug Description

I followed the [setup with docker simple](https://www.linkace.org/docs/v1/setup/setup-with-docker/simple/) instructions. When I connect to the Website, I get a `500 - Server Error: An internal server error occured. If you are the administrator, consult the application logs for details.`  Error. So I want to check the logs, but the folder is empty.

### How to reproduce

my docker-compose:
```
services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./db:/var/lib/mysql

  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:80:80"
      #- "0.0.0.0:443:443"
    volumes:
      - ./.env:/app/.env
      - ./backups:/app/storage/app/backups
      - ./linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:

```

my .env:
```
## LINKACE CONFIGURATION

## Please note that the LinkAce Docker image will be renamed with the release of LinkAce 2!
## Read more: https://github.com/Kovah/LinkAce/issues/502

## Basic app configuration
COMPOSE_PROJECT_NAME=linkace
# The app key is generated later, please leave it like that
APP_KEY=base64:pDrXiW6KgvUsZJWYwIRdw/JWvnz+Idz9oz1/1SPxD+c=

## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv, sqlite)
DB_CONNECTION=mysql
# Set the host of your database here
DB_HOST=db
# Set the port of your database here
DB_PORT=3306
# Set the database name here
DB_DATABASE=linkace
# Set both username and password of the user accessing the database
DB_USERNAME=linkace
# Wrap your password into quotes (") if it contains special characters
DB_PASSWORD=ChangeThisToASecurePassword!

## Redis cache configuration
# Set the Redis connection here if you want to use it
REDIS_HOST=redis
REDIS_PASSWORD=ChangeThisToASecurePassword!
REDIS_PORT=6379
```

### Expected behavior

I expected a more detailed error message or the setup website.

### LinkAce version

simple (v1.13.0-simple)

### Setup Method

Docker

### Operating System

Linux (Ubuntu, CentOS,...)

### Client details

- OS: Debian
