### ISSUE TITLE
Hello everyone, why did I deploy the project did not work properly, help me to see if the configuration file error

### ISSUE THREAD

**Issue by mopburn** [Kovah/LinkAce#866]
### Bug Description

Hello, I have just come into contact with Docker recently. In a nutshell, I deployed LinkAce on Win11, but it didn't perform as expected. After the deployment, I visited localhost:880 and couldn't enter it normally. It worked elsewhere. But it didn't work for LinkAce. I tried numerous things, but still couldn't figure out what was wrong. I am following the tutorial: https://www.linkace.org/docs/v1/setup/setup-with-docker/simple/
[linkace.zip](https://github.com/user-attachments/files/17814616/linkace.zip)

### Screenshots

![image](https://github.com/user-attachments/assets/472b94fe-0b29-4446-9808-cc18ed2241c9)
![image](https://github.com/user-attachments/assets/5a457b6f-38a3-46fa-bcb6-8550ebda8af8)
![image](https://github.com/user-attachments/assets/4f1e5c11-3b4c-4d21-a497-a66183ebc4c9)

### LinkAce version

v1.15

### Setup Method

Docker

### Operating System

Windows

### Client details

win11

**Comment by Kovah** [comment]
Hi, thanks for giving LinkAce a try.

Using port 880 inside the container won't work. You must bind your outside port (here 880) to port 80 inside the container. In the docker-compose file (if you are using it), it should look like this:
```yaml
  app:
    image: docker.io/linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:880:80" # <<-- this is correct
```

Also, not sure how Windows handles things, but you might prefer to use higher ports for your applications, as lover port ranges < 1000 are usually reserved for system services.
