### ISSUE TITLE
Error 500 for v2.1.2+

### ISSUE THREAD

**Issue by ckykenken** [Kovah/LinkAce#916]
Error 500 occured after I upgraded to version 2.1.3. 2.1.2 also no luck. Resumed service when rolled back to v2.1.1.
```
linkace-app-1  | ::1 -  16/Feb/2025:10:53:07 +0000 "GET /index.php" 404
linkace-app-1  | ::1 -  16/Feb/2025:10:53:31 +0000 "OPTIONS /index.php" 204
linkace-app-1  | ::1 -  16/Feb/2025:10:53:31 +0000 "GET /index.php" 404
linkace-app
```

![Image](https://github.com/user-attachments/assets/fb230d54-0853-4214-8daa-2df9be9253dd)

Using docker-compose in Proxmox container of Intel N100 hardware

**Comment by ckykenken** [comment]
docker-compose.yml:
```
version: "3"
services:
  # --- MariaDB
  db:
    image: docker.io/library/mariadb:11.2
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - /var/dockerdata/linkace/db:/var/lib/mysql
  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:v2.1.3
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 0.0.0.0:1796:80
      #- "0.0.0.0:443:443"
    environment:
      - PUID=65534
      - PGID=65534
    volumes:
      - /var/dockerdata/linkace/.env:/app/.env
      - /var/dockerdata/linkace/backups:/app/storage/app/backups
      - /var/dockerdata/linkace/logs:/app/storage/logs
      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro

volumes:
  db:
    driver: local
networks: {}
```

.env:
```
## LINKACE CONFIGURATION

## Please note that the LinkAce Docker image will be renamed with the release of LinkAce 2!
## Read more: https://github.com/Kovah/LinkAce/issues/502

## Basic app configuration
APP_URL=https://linkace.ckykenken.com
COMPOSE_PROJECT_NAME=linkace
# The app key is generated later, please leave it like that
APP_KEY=<REDACTED>
APP_DEBUG=true
## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv, sqlite)
DB_CONNECTION=mysql
# Set the host of your database here
DB_HOST=db
# Set the port of your database here
DB_PORT=3306
# Set the database name here
DB_DATABASE=linkace
# Set both username and password of the user accessing the database
DB_USERNAME=linkace
# Wrap your password into quotes (") if it contains special characters
DB_PASSWORD=<REDACTED>

## Redis cache configuration
# Set the Redis connection here if you want to use it
REDIS_HOST=redis
REDIS_PASSWORD=<REDACTED>
REDIS_PORT=6379

BACKUP_ENABLED=true
BACKUP_DISK=s3
AWS_ENDPOINT=<REDACTED>
AWS_ACCESS_KEY_ID=<REDACTED>
AWS_SECRET_ACCESS_KEY=<REDACTED>
AWS_BUCKET=linkace
AWS_DEFAULT_REGION=apac
```
