### ISSUE TITLE
LinkAce on Synology NAS (Container Manager)

### ISSUE THREAD

**Issue by nilsbyte** [Kovah/LinkAce#972]
I only found an issue from 2023 regarding LinkAce on Synology NAS so I am opening this issue.

I cannot get LinkAce to work. I have placed the `.env` file inside my Project root folder for the Container Manager project, along with the docker-compose.yml.

.env file:

```
## LINKACE CONFIGURATION

# The app key is generated later, please leave it like that
APP_KEY=someRandomStringWith32Characters

## Configuration of the database connection
## Attention: Those settings are configured during the web setup, please do not modify them now.
# Set the database driver (mysql, pgsql, sqlsrv, sqlite)
DB_CONNECTION=mysql
# Set the host of your database here
DB_HOST=db
# Set the port of your database here
DB_PORT=3306
# Set the database name here
DB_DATABASE=linkace
# Set both username and password of the user accessing the database
DB_USERNAME=linkace
# Wrap your password into quotes (") if it contains special characters
DB_PASSWORD=passworddb

## Redis cache configuration
# Set the Redis connection here if you want to use it
REDIS_HOST=redis
REDIS_PASSWORD=passwordredis
REDIS_PORT=6379
````

docker-compose.yml

```
services:
  # --- LinkAce
  app:
    image: docker.io/linkace/linkace:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3030:80"
    volumes:
      - /volume1/docker/linkace/.env:/app/.env
      # - /volume1/docker/linkace/backups:/app/storage/app/backups

  # --- Database
  db:
    image: docker.io/library/mariadb:11.5
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - /volume1/docker/linkace/db:/var/lib/mysql

  # --- Cache
  redis:
    image: docker.io/bitnami/redis:7.4
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  db:
````

Once the project and the containers are created, when trying to open http://SYNOLOGY_IP:3030 i get an empty response (tried curl, wget and browser). 

the log of the app container says:

```
2025/06/20 15:58:55 | stdout | 2025-06-20 13:58:55,145 INFO gave up: caddy entered FATAL state, too many start retries too quickly
-- | -- | --
2025/06/20 15:58:54 | stdout | 2025-06-20 13:58:54,144 WARN exited: caddy (exit status 1; not expected)
2025/06/20 15:58:54 | stderr | Error: loading initial config: loading new config: http app module: start: listening on :80: listen tcp :80: bind: permission denied
2025/06/20 15:58:54 | stderr | {"level":"info","ts":1750427934.1407945,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0002a3c00"}
2025/06/20 15:58:54 | stderr | {"level":"warn","ts":1750427934.1396782,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
2025/06/20 15:58:54 | stderr | {"level":"info","ts":1750427934.1392143,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//127.0.0.1:2019","//localhost:2019","//[::1]:2019"]}
2025/06/20 15:58:54 | stderr | {"level":"warn","ts":1750427934.137531,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
2025/06/20 15:58:54 | stderr | {"level":"info","ts":1750427934.1374888,"msg":"adapted config to JSON","adapter":"caddyfile"}
2025/06/20 15:58:54 | stderr | {"level":"info","ts":1750427934.1350987,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
2025/06/20 15:58:54 | stderr | {"level":"warn","ts":1750427934.1346052,"msg":"failed to set GOMAXPROCS","error":"open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory"}
2025/06/20 15:58:54 | stdout | 2025-06-20 13:58:54,035 INFO spawned: 'caddy' with pid 1289
2025/06/20 15:58:51 | stdout | 2025-06-20 13:58:51,030 WARN exited: caddy (exit status 1; not expected)
```
this repeats a couple times in the log.

where is the problem here? i think I got the non-simple version to work some time ago.

**Comment by nilsbyte** [comment]
Of course, I also tried the `:simple` version:

same .env

yml:

```
services:

  # --- LinkAce
  app:
    image: docker.io/linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "0.0.0.0:3030:80"
    volumes:
      - ./.env:/app/.env
      - /volume1/docker/linkace/backups:/app/storage/app/backups
      - /volume1/docker/linkace/logs:/app/storage/logs

  # --- Database
  db:
    image: docker.io/library/mariadb:11.5
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - /volume1/docker/linkace/db:/var/lib/mysql

volumes:
  linkace_logs:
  db:
    driver: local
```

now when loading the url http://SYNOLOGY_IP:3030 i get a red box with an internal server error.

the app container log:

```
2025/06/20 16:23:39 | stderr | 127.0.0.1 -  20/Jun/2025:14:23:39 +0000 "GET /index.php" 500
-- | -- | --
2025/06/20 16:23:39 | stdout | 172.27.0.1 - - [20/Jun/2025:14:23:39 +0000] "GET / HTTP/1.1" 500 5333 "http://192.168.3.99:3030/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36" "-"
2025/06/20 16:23:38 | stderr | 127.0.0.1 -  20/Jun/2025:14:23:37 +0000 "GET /index.php" 500
2025/06/20 16:23:38 | stdout | 172.27.0.1 - - [20/Jun/2025:14:23:38 +0000] "GET / HTTP/1.1" 500 5333 "http://192.168.3.99:3030/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36" "-"
2025/06/20 16:23:34 | stdout | 2025-06-20 14:23:34,608 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025/06/20 16:23:34 | stdout | 2025-06-20 14:23:34,608 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025/06/20 16:23:33 | stderr | [20-Jun-2025 14:23:33] NOTICE: ready to handle connections
2025/06/20 16:23:33 | stderr | [20-Jun-2025 14:23:33] NOTICE: fpm is running, pid 7
2025/06/20 16:23:33 | stdout | 2025-06-20 14:23:33,486 INFO spawned: 'nginx' with pid 8
2025/06/20 16:23:33 | stdout | 2025-06-20 14:23:33,482 INFO spawned: 'php-fpm' with pid 7
2025/06/20 16:23:32 | stdout | 2025-06-20 14:23:32,479 INFO supervisord started with pid 1
2025/06/20 16:23:32 | stdout | 2025-06-20 14:23:32,371 INFO Set uid to user 0 succeeded
```

after setting `APP_DEBUG=true` and opening the page in the browser, i get this error:

```
The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: file_put_contents(/app/.env): Failed to open stream: Permission denied
Context: {"exception":{}}
Context: {"exception":{}}
Context: {"exception":{}}
Context: {"exception":{}}
Context: {"exception":{}}
Context: {"exception":{}}
Context: {"exception":{}}
Context: {"exception":{}}
```

**Comment by nilsbyte** [comment]
`linkace:simple` is at version v1.16.1 ... so that is probably not an option to use. I would like to use regular `linkace` v2.x on Synology Container Manager. @Kovah can we sort this out somehow?

**Comment by Kovah** [comment]
> The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: file_put_contents(/app/.env): Failed to open stream: Permission denied

Please make sure that the .env file is writable for the setup. It also seems that there's something wrong with the logs folder, too. Please make it writable as well.

**Comment by nilsbyte** [comment]
> > The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2025-06-20.log" could not be opened in append mode: Failed to open stream: Permission denied
> > The exception occurred while attempting to log: file_put_contents(/app/.env): Failed to open stream: Permission denied
> 
> Please make sure that the .env file is writable for the setup. It also seems that there's something wrong with the logs folder, too. Please make it writable as well.

Yes, I don't know why but there is a permissions problem. I have to allow Read/Write access for 'everyone' for the `logs` folder and the `.env` file, then it works, but only the `:simple` version which is at 1.x.

Is it possible to get the regular version (v2.x) working with Container Manager? I pasted the log above.

**Comment by Kovah** [comment]
> listen tcp :80: bind: permission denied

If the LinkAce container is not starting, this might be caused by OS-specific permissions for Docker. In that case, try to run LinkAce on another internal port:
docker run -p "8080:8080" -e "PORT=8080" -v "./database.sqlite:/app/database/database.sqlite" linkace/linkace

See https://www.linkace.org/docs/v2/setup/setup-with-docker/

**Comment by nilsbyte** [comment]
> > listen tcp :80: bind: permission denied
> 
> If the LinkAce container is not starting, this might be caused by OS-specific permissions for Docker. In that case, try to run LinkAce on another internal port: docker run -p "8080:8080" -e "PORT=8080" -v "./database.sqlite:/app/database/database.sqlite" linkace/linkace
> 
> See https://www.linkace.org/docs/v2/setup/setup-with-docker/

Okay, I added the environment variable `PORT` with `8080` and my `yml` worked. It looks like the Docker process on Synology NAS does not have permission to use port 80 inside a container...? Well, I got the default `yml` file to work now, with MySQL instead of SQLite. Thanks @Kovah 

Here is my `yml` for reference:

```
services:

  # --- LinkAce
  app:
    image: docker.io/linkace/linkace:latest
    container_name: linkace-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "43956:8080"
    environment: 
      - PORT=8080
    volumes:
      - /volume1/docker/linkace/.env:/app/.env
      - /volume1/docker/linkace/backups:/app/storage/app/backups
      - /volume1/docker/linkace/logs:/app/storage/logs

  # --- Database
  db:
    image: docker.io/library/mariadb:11.5
    container_name: linkace-db
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - /volume1/docker/linkace/db:/var/lib/mysql

  # --- Cache
  redis:
    image: docker.io/bitnami/redis:7.4
    container_name: linkace-cache
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
```
